version: '3.7'

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration_dev
      POSTGRES_HOST: localhost
    image: postgres
    expose:
      - 5432
    networks:
      - default
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

volumes:
  pgdata: