"""add password column to student

Revision ID: 3eaa4c7dbfe5
Revises: b74078be6cfc
Create Date: 2020-07-11 20:09:19.553612

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3eaa4c7dbfe5'
down_revision = 'b74078be6cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password', sa.String(length=256), nullable=False, server_default=""))
    op.create_unique_constraint(None, 'students', ['phone_number'])
    op.create_unique_constraint(None, 'students', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'password')
    # ### end Alembic commands ###
