"""add image url

Revision ID: 8921a096157b
Revises: b40fa0180116
Create Date: 2020-06-24 15:41:17.407659

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8921a096157b'
down_revision = 'b40fa0180116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    op.add_column('students', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'image_url')
    op.create_table('student_courses',
                    sa.Column('student_course_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('student_id', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('course_id', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'],
                                            name='student_courses_course_id_fkey'),
                    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'],
                                            name='student_courses_student_id_fkey'),
                    sa.PrimaryKeyConstraint('student_course_id', name='student_courses_pkey')
                    )
    # ### end Alembic commands ###
