"""add image url

Revision ID: 8921a096157b
Revises: b40fa0180116
Create Date: 2020-06-24 15:41:17.407659

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8921a096157b'
down_revision = 'b40fa0180116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('image_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'image_url')
    # ### end Alembic commands ###
