"""rename columns

Revision ID: b40fa0180116
Revises: c39d532b11cd
Create Date: 2020-06-21 20:34:43.016901

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b40fa0180116'
down_revision = 'c39d532b11cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute(
        'ALTER TABLE students ALTER COLUMN id DROP DEFAULT, ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4()), ALTER COLUMN id SET DEFAULT uuid_generate_v4()')
    op.alter_column('students', 'id', nullable=False, new_column_name='student_id')
    op.alter_column('courses', 'id', nullable=False, new_column_name='course_id')
    op.alter_column('courses', 'code', nullable=False, new_column_name='course_code')
    op.alter_column('courses', 'name', nullable=False, new_column_name='course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students',
                  sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False,
                            nullable=False))
    op.drop_column('students', 'student_id')
    op.add_column('courses', sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('courses', 'course_name')
    op.drop_column('courses', 'course_id')
    op.drop_column('courses', 'course_code')
    # ### end Alembic commands ###
