"""add student course association

Revision ID: b74078be6cfc
Revises: 8921a096157b
Create Date: 2020-07-09 15:42:53.307699

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b74078be6cfc'
down_revision = '8921a096157b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
                    sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
                    sa.PrimaryKeyConstraint('student_id', 'course_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_courses')
    # ### end Alembic commands ###
