"""add course table

Revision ID: c39d532b11cd
Revises: ec072120a086
Create Date: 2020-06-21 14:34:57.948580

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c39d532b11cd'
down_revision = 'ec072120a086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('code', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(length=256), nullable=True),
                    sa.Column('instructor', sa.String(length=50), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
