"""add active column to student

Revision ID: ec072120a086
Revises: 3496f3637a61
Create Date: 2020-06-21 00:45:15.843267

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec072120a086'
down_revision = '3496f3637a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'active')
    # ### end Alembic commands ###
